a_link = "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
podium_block = "w-full h-%s bg-gray-200 flex flex-col justify-center items-center space-y-4"
container = "lg:w-2/3 md:w-2/3 sm:w-3/4 w-full mx-auto "
input_style = "w-full border border-gray-300 rounded-md py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
btn_primary = "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
label = "text-xl text-center font-bold text-gray-500"
input_container = "flex flex-col justify-center items-center space-y-4"
